import { Option } from "@/_types/select";

export const ROLES: Option[] = [
  { label: "Content Creator", value: "contentCreator" },
  { label: "Photographer", value: "photographer" },
  { label: "Videographer", value: "videographer" },
  { label: "Photo Editor", value: "photoEditor" },
  { label: "Video Editor", value: "videoEditor" },
  { label: "Graphic Designer", value: "graphicDesigner" },
  { label: "Blogger", value: "blogger" },
  { label: "Vlogger", value: "vlogger" },
  { label: "Social Media Manager", value: "socialMediaManager" },
  { label: "SEO Specialist", value: "seoSpecialist" },
  { label: "Copywriter", value: "copywriter" },
  { label: "Public Relations Specialist", value: "publicRelationsSpecialist" },
  { label: "Brand Collaborator", value: "brandCollaborator" },
  { label: "Influencer Marketer", value: "influencerMarketer" },
  { label: "Digital Marketer", value: "digitalMarketer" },
  { label: "Email Marketer", value: "emailMarketer" },
  { label: "Podcaster", value: "podcaster" },
  { label: "Event Planner", value: "eventPlanner" },
  { label: "Fashion Stylist", value: "fashionStylist" },
  { label: "Makeup Artist", value: "makeupArtist" },
  { label: "Fitness Trainer", value: "fitnessTrainer" },
  { label: "Health Coach", value: "healthCoach" },
  { label: "Travel Blogger", value: "travelBlogger" },
  { label: "Food Blogger", value: "foodBlogger" },
  { label: "Recipe Developer", value: "recipeDeveloper" },
  { label: "Home Decor Expert", value: "homeDecorExpert" },
  { label: "DIY Specialist", value: "diySpecialist" },
  { label: "Parenting Advisor", value: "parentingAdvisor" },
  { label: "Tech Reviewer", value: "techReviewer" },
  { label: "Product Reviewer", value: "productReviewer" },
  { label: "Live Streamer", value: "liveStreamer" },
  {
    label: "Customer Engagement Specialist",
    value: "customerEngagementSpecialist",
  },
  { label: "Brand Ambassador", value: "brandAmbassador" },
  { label: "Contest Manager", value: "contestManager" },
  { label: "Giveaway Coordinator", value: "giveawayCoordinator" },
  { label: "Web Designer", value: "webDesigner" },
  { label: "App Developer", value: "appDeveloper" },
  { label: "UX/UI Designer", value: "uxUiDesigner" },
  { label: "Project Manager", value: "projectManager" },
  { label: "Data Analyst", value: "dataAnalyst" },
  { label: "Market Researcher", value: "marketResearcher" },
  { label: "Audience Growth Specialist", value: "audienceGrowthSpecialist" },
  { label: "Community Builder", value: "communityBuilder" },
  { label: "Trend Analyst", value: "trendAnalyst" },
  { label: "Networker", value: "networker" },
  {
    label: "Influencer Outreach Specialist",
    value: "influencerOutreachSpecialist",
  },
  { label: "Campaign Strategist", value: "campaignStrategist" },
  { label: "Content Strategist", value: "contentStrategist" },
  { label: "Scheduler", value: "scheduler" },
  { label: "Time Management Specialist", value: "timeManagementSpecialist" },
  { label: "Task Automation Specialist", value: "taskAutomationSpecialist" },
  { label: "Script Writer", value: "scriptWriter" },
  { label: "Voice Over Artist", value: "voiceOverArtist" },
  { label: "Host", value: "host" },
  { label: "Interviewer", value: "interviewer" },
  { label: "Panel Moderator", value: "panelModerator" },
  { label: "Webinar Host", value: "webinarHost" },
  { label: "E-commerce Specialist", value: "eCommerceSpecialist" },
  { label: "Sales Funnel Specialist", value: "salesFunnelSpecialist" },
  { label: "Lead Generation Specialist", value: "leadGenerationSpecialist" },
  {
    label: "Conversion Optimization Specialist",
    value: "conversionOptimizationSpecialist",
  },
  { label: "Customer Service Specialist", value: "customerServiceSpecialist" },
  { label: "CRM Specialist", value: "crmSpecialist" },
  { label: "PPC Advertising Specialist", value: "ppcAdvertisingSpecialist" },
  { label: "Google Analytics Specialist", value: "googleAnalyticsSpecialist" },
  { label: "Facebook Ads Specialist", value: "facebookAdsSpecialist" },
  { label: "Instagram Ads Specialist", value: "instagramAdsSpecialist" },
  { label: "Twitter Ads Specialist", value: "twitterAdsSpecialist" },
  { label: "LinkedIn Ads Specialist", value: "linkedinAdsSpecialist" },
  { label: "Snapchat Ads Specialist", value: "snapchatAdsSpecialist" },
  { label: "TikTok Ads Specialist", value: "tiktokAdsSpecialist" },
  { label: "YouTube Ads Specialist", value: "youtubeAdsSpecialist" },
  { label: "Pinterest Ads Specialist", value: "pinterestAdsSpecialist" },
  { label: "Affiliate Marketer", value: "affiliateMarketer" },
  { label: "Monetization Specialist", value: "monetizationSpecialist" },
  { label: "Sponsorship Negotiator", value: "sponsorshipNegotiator" },
  { label: "Contracts Specialist", value: "contractsSpecialist" },
  { label: "Legal Compliance Specialist", value: "legalComplianceSpecialist" },
  { label: "Accountant", value: "accountant" },
  { label: "Bookkeeper", value: "bookkeeper" },
  { label: "Budgeting Specialist", value: "budgetingSpecialist" },
  { label: "Financial Planner", value: "financialPlanner" },
  { label: "Tax Preparer", value: "taxPreparer" },
  { label: "Investment Strategist", value: "investmentStrategist" },
  { label: "Fundraiser", value: "fundraiser" },
  { label: "Crowdfunding Specialist", value: "crowdfundingSpecialist" },
  { label: "Public Speaker", value: "publicSpeaker" },
  { label: "Workshop Facilitator", value: "workshopFacilitator" },
  { label: "Trainer", value: "trainer" },
  { label: "Mentor", value: "mentor" },
  { label: "Coach", value: "coach" },
  { label: "Advisor", value: "advisor" },
  { label: "Consultant", value: "consultant" },
  { label: "Team Builder", value: "teamBuilder" },
  { label: "Conflict Resolver", value: "conflictResolver" },
  { label: "Motivator", value: "motivator" },
  { label: "Leader", value: "leader" },
  { label: "Crisis Manager", value: "crisisManager" },
  { label: "Content Moderator", value: "contentModerator" },
  { label: "User Experience Researcher", value: "userExperienceResearcher" },
  { label: "Brand Strategist", value: "brandStrategist" },
  { label: "Media Buyer", value: "mediaBuyer" },
  { label: "Creative Director", value: "creativeDirector" },
  { label: "Art Director", value: "artDirector" },
  { label: "Social Media Analyst", value: "socialMediaAnalyst" },
  { label: "Event Coordinator", value: "eventCoordinator" },
  { label: "Talent Manager", value: "talentManager" },
  { label: "Influencer Agent", value: "influencerAgent" },
  { label: "Content Scheduler", value: "contentScheduler" },
  { label: "Editorial Director", value: "editorialDirector" },
  { label: "Feature Writer", value: "featureWriter" },
  { label: "Columnist", value: "columnist" },
  { label: "Community Manager", value: "communityManager" },
  { label: "Forum Moderator", value: "forumModerator" },
  { label: "Content Curator", value: "contentCurator" },
  { label: "Online Course Creator", value: "onlineCourseCreator" },
  {
    label: "Learning Management System Specialist",
    value: "learningManagementSystemSpecialist",
  },
  { label: "E-learning Specialist", value: "elearningSpecialist" },
  { label: "Membership Site Manager", value: "membershipSiteManager" },
  {
    label: "Subscription Service Manager",
    value: "subscriptionServiceManager",
  },
  { label: "Webinar Producer", value: "webinarProducer" },
  { label: "Virtual Summit Organizer", value: "virtualSummitOrganizer" },
  { label: "Affiliate Program Manager", value: "affiliateProgramManager" },
  { label: "Dropshipping Specialist", value: "dropshippingSpecialist" },
  { label: "Supply Chain Manager", value: "supplyChainManager" },
  { label: "Inventory Manager", value: "inventoryManager" },
  { label: "Shipping Coordinator", value: "shippingCoordinator" },
  { label: "Warehouse Manager", value: "warehouseManager" },
  { label: "Fulfillment Specialist", value: "fulfillmentSpecialist" },
  { label: "Customer Support Specialist", value: "customerSupportSpecialist" },
  {
    label: "Technical Support Specialist",
    value: "technicalSupportSpecialist",
  },
  { label: "Client Success Manager", value: "clientSuccessManager" },
  { label: "Account Manager", value: "accountManager" },
  { label: "Sales Representative", value: "salesRepresentative" },
  {
    label: "Business Development Manager",
    value: "businessDevelopmentManager",
  },
  { label: "Partnership Manager", value: "partnershipManager" },
  {
    label: "Franchise Development Manager",
    value: "franchiseDevelopmentManager",
  },
  { label: "Retail Manager", value: "retailManager" },
  { label: "Store Manager", value: "storeManager" },
  { label: "Visual Merchandiser", value: "visualMerchandiser" },
  { label: "Buyer", value: "buyer" },
  { label: "Product Manager", value: "productManager" },
  { label: "Merchandising Manager", value: "merchandisingManager" },
  { label: "Quality Control Specialist", value: "qualityControlSpecialist" },
  {
    label: "Regulatory Affairs Specialist",
    value: "regulatoryAffairsSpecialist",
  },
  { label: "Compliance Manager", value: "complianceManager" },
  { label: "Risk Manager", value: "riskManager" },
  { label: "Safety Manager", value: "safetyManager" },
  {
    label: "Environmental Health Specialist",
    value: "environmentalHealthSpecialist",
  },
  { label: "Sustainability Coordinator", value: "sustainabilityCoordinator" },
  {
    label: "Corporate Social Responsibility Specialist",
    value: "corporateSocialResponsibilitySpecialist",
  },
  { label: "Public Policy Manager", value: "publicPolicyManager" },
  {
    label: "Government Relations Specialist",
    value: "governmentRelationsSpecialist",
  },
  { label: "Lobbyist", value: "lobbyist" },
  { label: "Grant Writer", value: "grantWriter" },
  { label: "Nonprofit Program Manager", value: "nonprofitProgramManager" },
  { label: "Fund Development Manager", value: "fundDevelopmentManager" },
  { label: "Philanthropy Manager", value: "philanthropyManager" },
  { label: "Volunteer Coordinator", value: "volunteerCoordinator" },
  { label: "Alumni Relations Manager", value: "alumniRelationsManager" },
  {
    label: "University Relations Specialist",
    value: "universityRelationsSpecialist",
  },
  { label: "Career Services Advisor", value: "careerServicesAdvisor" },
  { label: "Student Success Coach", value: "studentSuccessCoach" },
  { label: "Academic Advisor", value: "academicAdvisor" },
  { label: "Enrollment Specialist", value: "enrollmentSpecialist" },
  { label: "Admissions Counselor", value: "admissionsCounselor" },
  { label: "Financial Aid Specialist", value: "financialAidSpecialist" },
  { label: "Registrar", value: "registrar" },
  { label: "Curriculum Developer", value: "curriculumDeveloper" },
  { label: "Instructional Designer", value: "instructionalDesigner" },
  { label: "Educational Consultant", value: "educationalConsultant" },
  { label: "Learning Specialist", value: "learningSpecialist" },
  { label: "Tutor", value: "tutor" },
  { label: "Teacher", value: "teacher" },
  { label: "Professor", value: "professor" },
  { label: "Researcher", value: "researcher" },
  { label: "Lab Technician", value: "labTechnician" },
  { label: "Clinical Trial Coordinator", value: "clinicalTrialCoordinator" },
  {
    label: "Pharmaceutical Sales Representative",
    value: "pharmaceuticalSalesRepresentative",
  },
  { label: "Medical Science Liaison", value: "medicalScienceLiaison" },
  { label: "Healthcare Administrator", value: "healthcareAdministrator" },
  { label: "Medical Billing Specialist", value: "medicalBillingSpecialist" },
  { label: "Medical Coder", value: "medicalCoder" },
  { label: "Patient Advocate", value: "patientAdvocate" },
  {
    label: "Health Information Technician",
    value: "healthInformationTechnician",
  },
  { label: "Clinical Data Manager", value: "clinicalDataManager" },
  { label: "Public Health Analyst", value: "publicHealthAnalyst" },
  { label: "Epidemiologist", value: "epidemiologist" },
  { label: "Biostatistician", value: "biostatistician" },
  { label: "Health Educator", value: "healthEducator" },
  { label: "Wellness Coordinator", value: "wellnessCoordinator" },
];
