export const SKILLS: { label: string; value: string }[] = [
  { label: "Content Creation", value: "contentCreation" },
  { label: "Photography", value: "photography" },
  { label: "Videography", value: "videography" },
  { label: "Photo Editing", value: "photoEditing" },
  { label: "Video Editing", value: "videoEditing" },
  { label: "Graphic Design", value: "graphicDesign" },
  { label: "Blogging", value: "blogging" },
  { label: "Vlogging", value: "vlogging" },
  { label: "Social Media Management", value: "socialMediaManagement" },
  { label: "SEO", value: "seo" },
  { label: "Copywriting", value: "copywriting" },
  { label: "Public Relations", value: "publicRelations" },
  { label: "Brand Collaboration", value: "brandCollaboration" },
  { label: "Influencer Marketing", value: "influencerMarketing" },
  { label: "Digital Marketing", value: "digitalMarketing" },
  { label: "Email Marketing", value: "emailMarketing" },
  { label: "Podcasting", value: "podcasting" },
  { label: "Event Planning", value: "eventPlanning" },
  { label: "Fashion Styling", value: "fashionStyling" },
  { label: "Makeup Artistry", value: "makeupArtistry" },
  { label: "Fitness Training", value: "fitnessTraining" },
  { label: "Health Coaching", value: "healthCoaching" },
  { label: "Travel Blogging", value: "travelBlogging" },
  { label: "Food Blogging", value: "foodBlogging" },
  { label: "Recipe Development", value: "recipeDevelopment" },
  { label: "Home Decor", value: "homeDecor" },
  { label: "DIY Projects", value: "diyProjects" },
  { label: "Parenting Tips", value: "parentingTips" },
  { label: "Tech Reviews", value: "techReviews" },
  { label: "Product Reviews", value: "productReviews" },
  { label: "Live Streaming", value: "liveStreaming" },
  { label: "Customer Engagement", value: "customerEngagement" },
  { label: "Brand Ambassadorship", value: "brandAmbassadorship" },
  { label: "Contest Management", value: "contestManagement" },
  { label: "Giveaways", value: "giveaways" },
  { label: "Web Design", value: "webDesign" },
  { label: "App Development", value: "appDevelopment" },
  { label: "UX/UI Design", value: "uxUiDesign" },
  { label: "Project Management", value: "projectManagement" },
  { label: "Data Analysis", value: "dataAnalysis" },
  { label: "Analytics", value: "analytics" },
  { label: "Market Research", value: "marketResearch" },
  { label: "Audience Growth", value: "audienceGrowth" },
  { label: "Community Building", value: "communityBuilding" },
  { label: "Trend Analysis", value: "trendAnalysis" },
  { label: "Networking", value: "networking" },
  { label: "Influencer Outreach", value: "influencerOutreach" },
  { label: "Campaign Strategy", value: "campaignStrategy" },
  { label: "Content Strategy", value: "contentStrategy" },
  { label: "Scheduling", value: "scheduling" },
  { label: "Time Management", value: "timeManagement" },
  { label: "Task Automation", value: "taskAutomation" },
  { label: "Script Writing", value: "scriptWriting" },
  { label: "Voice Over", value: "voiceOver" },
  { label: "Hosting", value: "hosting" },
  { label: "Interviewing", value: "interviewing" },
  { label: "Panel Moderation", value: "panelModeration" },
  { label: "Webinars", value: "webinars" },
  { label: "E-commerce", value: "eCommerce" },
  { label: "Sales Funnels", value: "salesFunnels" },
  { label: "Lead Generation", value: "leadGeneration" },
  { label: "Conversion Optimization", value: "conversionOptimization" },
  { label: "Customer Service", value: "customerService" },
  { label: "CRM", value: "crm" },
  { label: "PPC Advertising", value: "ppcAdvertising" },
  { label: "Google Analytics", value: "googleAnalytics" },
  { label: "Facebook Ads", value: "facebookAds" },
  { label: "Instagram Ads", value: "instagramAds" },
  { label: "Twitter Ads", value: "twitterAds" },
  { label: "LinkedIn Ads", value: "linkedinAds" },
  { label: "Snapchat Ads", value: "snapchatAds" },
  { label: "TikTok Ads", value: "tiktokAds" },
  { label: "YouTube Ads", value: "youtubeAds" },
  { label: "Pinterest Ads", value: "pinterestAds" },
  { label: "Affiliate Marketing", value: "affiliateMarketing" },
  { label: "Monetization", value: "monetization" },
  { label: "Sponsorship Negotiation", value: "sponsorshipNegotiation" },
  { label: "Contracts", value: "contracts" },
  { label: "Legal Compliance", value: "legalCompliance" },
  { label: "Accounting", value: "accounting" },
  { label: "Bookkeeping", value: "bookkeeping" },
  { label: "Budgeting", value: "budgeting" },
  { label: "Financial Planning", value: "financialPlanning" },
  { label: "Tax Preparation", value: "taxPreparation" },
  { label: "Investment Strategies", value: "investmentStrategies" },
  { label: "Fundraising", value: "fundraising" },
  { label: "Crowdfunding", value: "crowdfunding" },
  { label: "Public Speaking", value: "publicSpeaking" },
  { label: "Workshop Facilitation", value: "workshopFacilitation" },
  { label: "Training", value: "training" },
  { label: "Mentoring", value: "mentoring" },
  { label: "Coaching", value: "coaching" },
  { label: "Advising", value: "advising" },
  { label: "Consulting", value: "consulting" },
  { label: "Team Building", value: "teamBuilding" },
  { label: "Conflict Resolution", value: "conflictResolution" },
  { label: "Motivation", value: "motivation" },
  { label: "Leadership", value: "leadership" },
];
